
[build]
  command = "npm install"
  publish = "public"  # Dossier contenant les fichiers statiques (HTML, CSS, JS)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
